### PR TITLE
Aws lambda deploy en

### PR DESCRIPTION
**Pull request by Mantis-Ranson**
English translation of Aws lambda deploy.

### CODE REVIEW

**Comment by k-harada413** [comment]
キャプチャの管理ってどうしますか？gyazoとレポジトリ内で混在してるように見えます。
私はレポジトリ管理の方がいいと思います。

How do we manage image file? It looks mixed gyazo and repository management.
I would think repository management better.

**Comment by Mantis-Ranson** [comment]
Yeah. Better but I was following the same design as what heima did. Arrows,
blur and boxes.

**Comment by k-harada413** [comment]
編集方法は平間さんの方針でいいと思います。
画像の編集方法ではなくて、私が指摘したのは画像の保存場所ですね。

I think Image design is like these good.
But I point out where to save images, not how to edit one.

**Comment by Mantis-Ranson** [comment]
I think a good Idea is make an enebular/docs team here.
We can edit and save images here.
what do you guys think?


​

**Comment by k-harada413** [comment]
I think it too.
Images are saved in this repository.

**Comment by Mantis-Ranson** [comment]
pro and team cost money though....

**Pull request closed without merging**
